# -*- coding: utf-8 -*-
#
# Chef documentation build configuration file, created by
# sphinx-quickstart on Wed Feb 22 13:50:49 2012.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys, os

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#sys.path.insert(0, os.path.abspath('.'))

#sys.path.append(os.path.abspath('../../_ext'))

# -- General configuration -----------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be extensions
# coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = ['hieroglyph']

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates', '../../_templates']

# The suffix of source filenames.
source_suffix = '.rst'

# The encoding of source files.
#source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'index'

# General information about the project.
project = u'MARKUP Theme'
#copyright = u''

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
# version = '0.0.1'
# The full version, including alpha/beta/rc tags.
# release = '0.0.1-1'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#language = None

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
#today = ''
# Else, today_fmt is used as the format for a strftime call.
#today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = []

# The reST default role (used for this markup: `text`) to use for all documents.
#default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
#add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
#add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
#show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'friendly'

# highlight_language = 'ruby'

# A list of ignored prefixes for module index sorting.
#modindex_common_prefix = []

# A string of reStructuredText that will be included at the beginning of every source file that is read.
rst_prolog = """
.. include:: ../../tokens/names.txt
"""

# -- Options for HTML Slide output ---------------------------------------------------

# Default: True
# When autoslides is True, Hieroglyph will generate slides from the document sections. If autoslides is set to False, only generate slides from the slide directive.
# This can be overridden on a per-document basis using the slideconf directive.

autoslides = True


# Default: slides
# The theme to use when generating slides. Hieroglyph includes two themes, slides and single-level.
# This can be overridden on a per-document basis using the slideconf directive.

slide_theme = 'slides-hieroglyph'


# Default: 3
# Number of Sphinx section levels to convert to slides; note that the document title is level 1. Heading levels greater than slide levels will simply be treated as slide content.

slide_levels = 3


# Default: False
# If set to True, slide numbers will be added to the HTML output.

slide_numbers = True


# Default: None
# Text that will be added to the bottom of every slide.
# This is disabled on purpose
#slide_footer = "Welcome to Slides!"
slide_footer = ""

# Default: {}
# Theme specific options as a dict.

#slide_theme_options = {'custom_css':'slides.css'}


# Default: [].
# A list of paths to look for themes in.

slide_theme_path = ['../../_themes/']


# Default: False
# Link from slides to HTML.

slide_link_to_html = True


# Default: False
# Link from HTML to slides.
# For example: slide_link_html_to_slides = not on_rtd

slide_link_html_to_slides = False


# Default: False
# Link individual HTML sections to specific slides.
# Note that slide_link_html_to_slides must be enabled for this to have any effect.
# For example: slide_link_html_sections_to_slides = not on_rtd

slide_link_html_sections_to_slides = False


# Relative path from HTML to slides; default: ../slides/

slide_relative_path = "./slides/"


# Relative path from slides to HTML; default: ../html/

slide_html_relative_path = "../"

